### ISSUE TITLE
question about settings 

### ISSUE THREAD

**Issue by dadinugroho** [andreccosta/wordpress-xdebug-dockerbuild#3]
Hi @andreccosta,

May I ask you two questions,

1. Is there any significant why we set the port as 9000? Is not that the new port is 9003 for XDEBUG 3.x.x? I have tried both port 9000 and 9003 and they are working. 
2. I am newbie in Docker. Is there any significant that we set the similar things in `Dockerfile` and `docker-compose.yml`?

`Dockerfile`
```
...
RUN echo "xdebug.mode=develop,debug" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.discover_client_host=true" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_port=${XDEBUG_PORT}" >> /usr/local/etc/php/conf.d/xdebug.ini
...
```

`docker-compose.yml`
```
...
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: discover_client_host=true start_with_request=yes client_host=host.docker.internal client_port=9000
...
```

I tried to remove the settings in `docker-compose.yml` and it is still working, but it is not working when I remove the settings in `Dockerfile`. 

Thank you.

**Comment by andreccosta** [comment]
Hello @dadinugroho,

Sure. Xdebug 3 transitioned to using port 9003 by default instead of 9000. The only reason behind sticking with 9000 by default here is to not break existing configurations (even if you update the image). But you like you mentioned you can easily override that.
The difference between the two highlighted pieces of code is that one is setting those values in the configuration file (`Dockerfile`) and the other is setting them via environment variables (`docker-compose.yml`). Configured values via environment variables take precedence over those set via configuration file.

Just one additional note. You don't need to clone this repo in order to use it unless you want to modify the `Dockerfile` and build it yourself.
Otherwise you can just use the image directly either via Docker Hub or Github itself (and then use it as part of a docker-compose or any other container orchestration you might prefer):

```
docker pull andreccosta/wordpress-xdebug
```
or
```
docker pull docker.pkg.github.com/andreccosta/wordpress-xdebug-dockerbuild/wordpress-xdebug
```

Feel free to reopen this if you have any additional questions.

**Comment by dadinugroho** [comment]
Hi @andreccosta, thank you for your comprehensive explanation. I have learned a lot from this. One more question, If I do not add the settings in the `Dockerfile`, but I added them in `docker-compose.yml`, my `vscode` is not responding to the `XDEBUG`. Would you mind elaborating more on this? 

Thank you in advance.
